import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class userCreation extends javax.swing.JInternalFrame {

  private javax.swing.JButton buttonAddUser;
  private javax.swing.JButton buttonCancel;
  private javax.swing.JLabel labelUserId;
  private javax.swing.JLabel labelUserFirstName;
  private javax.swing.JLabel labelUserLastName;
  private javax.swing.JLabel labelUsername;
  private javax.swing.JLabel labelPassword;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtfirstname;
  private javax.swing.JTextField txtlastname;
  private javax.swing.JPasswordField txtpassword;
  private javax.swing.JLabel txtuserid;
  private javax.swing.JTextField txtusername;
  private javax.swing.JLabel status;

  /** Creates new form userCreation **/
  public userCreation() {
    initComponents();
    autoID();
  }

  Connection con;
  PreparedStatement pst;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel1.setName("userCreationPanel");
    labelUserId = new javax.swing.JLabel();
    labelUserFirstName = new javax.swing.JLabel();
    labelUserLastName = new javax.swing.JLabel();
    labelUsername = new javax.swing.JLabel();
    labelPassword = new javax.swing.JLabel();
    txtuserid = new javax.swing.JLabel();
    txtuserid.setName("textUserId");
    txtfirstname = new javax.swing.JTextField();
    txtfirstname.setName("textFirstName");
    txtlastname = new javax.swing.JTextField();
    txtlastname.setName("textLastName");
    txtusername = new javax.swing.JTextField();
    txtusername.setName("textUserName");
    buttonAddUser = new javax.swing.JButton();
    buttonAddUser.setName("buttonAdd");
    buttonCancel = new javax.swing.JButton();
    buttonCancel.setName("buttonCancel");
    txtpassword = new javax.swing.JPasswordField();
    txtpassword.setName("textPassword");
    status = new javax.swing.JLabel();
    status.setName("statustext");

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User Creation"));

    labelUserId.setFont(new java.awt.Font("Tahoma", 1, 12));
    labelUserId.setText("User ID");

    labelUserFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelUserFirstName.setText("FirstName");

    labelUserLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelUserLastName.setText("LastName");

    labelUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelUsername.setText("User Name");

    labelPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelPassword.setText("Password");

    txtuserid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txtuserid.setForeground(new java.awt.Color(255, 0, 0));
    txtuserid.setText("jLabel6");

    buttonAddUser.setText("Add");
    buttonAddUser.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            insertUserIntoDatabase(evt);
          }
        });

    buttonCancel.setText("Cancel");
    buttonCancel.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonCancelAction(evt);
          }
        });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUserId)
                            .addComponent(labelUserFirstName)
                            .addComponent(labelUserLastName)
                            .addComponent(labelUsername)
                            .addComponent(labelPassword))
                    .addGap(55, 55, 55)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuserid)
                            .addComponent(txtfirstname)
                            .addComponent(txtlastname)
                            .addComponent(txtusername)
                            .addComponent(
                                txtpassword,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                140,
                                Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(
                        status,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        109,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                            buttonAddUser,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        109,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                            buttonCancel,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        107,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGroup(
                                                        jPanel1Layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .BASELINE)
                                                            .addComponent(labelUserId)
                                                            .addComponent(txtuserid))
                                                    .addGap(37, 37, 37)
                                                    .addGroup(
                                                        jPanel1Layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .BASELINE)
                                                            .addComponent(labelUserFirstName)
                                                            .addComponent(
                                                                txtfirstname,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE))
                                                    .addGap(44, 44, 44)
                                                    .addComponent(labelUserLastName))
                                            .addComponent(
                                                txtlastname,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addComponent(labelUsername))
                            .addComponent(
                                txtusername,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPassword)
                            .addComponent(
                                txtpassword,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                status,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                    buttonAddUser,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                48,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                    buttonCancel,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                44,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(
                        jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(
                        jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void insertUserIntoDatabase(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    String id = txtuserid.getText();
    String firstname = txtfirstname.getText();
    String lastname = txtlastname.getText();
    String username = txtusername.getText();
    String password = txtpassword.getText();

    if (username.length() >= 8 && username.length() <= 20) {
      status.setText("pass");
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
        pst =
            con.prepareStatement(
                "insert into user(id,firstname,lastname,username,password)values(?,?,?,?,?)");

        pst.setString(1, id);
        pst.setString(2, firstname);
        pst.setString(3, lastname);
        pst.setString(4, username);
        pst.setString(5, password);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "User Createdd.........");
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
        Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
      }
    } else {
      status.setText("fail");
    }
  } // GEN-LAST:event_jButton1ActionPerformed

  private void buttonCancelAction(
      java.awt.event.ActionEvent evt) {
    this.hide();
  }

  public void autoID() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      Statement s = con.createStatement();
      ResultSet rs = s.executeQuery("select MAX(id) from user");
      rs.next();
      rs.getString("MAX(id)");
      if (rs.getString("MAX(id)") == null) {
        txtuserid.setText("UO001");
      } else {
        long id =
            Long.parseLong(rs.getString("MAX(id)").substring(2, rs.getString("MAX(id)").length()));
        id++;
        txtuserid.setText("UO" + String.format("%03d", id));
      }

    } catch (ClassNotFoundException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

}
